import _PageCard from './pageCard';
import _PageMedia from './pageMedia';
import _PageTitle from './pageTitle';
import _PageText from './pageText';
import _PageImage from './pageImage';
import _PageBody from './pageBody';
export {Float} from '../../constants/styles';
export {StylePaper, Display, Position} from '../../common/paper';
export const PageCard = _PageCard;
export const PageMedia = _PageMedia;
export const PageTitle = _PageTitle;
export const PageText = _PageText;
export const PageBody = _PageBody;
export const PageImage = _PageImage;