export default {
    CREATE_SUCCESS_ALERT: 'CREATE_SUCCESS_ALERT',
    CREATE_FAILURE_ALERT: 'CREATE_FAILURE_ALERT',
    CREATE_ALERT: 'CREATE_ALERT',
    UPDATE_ALERT_QUEUE: 'UPDATE_ALERT_QUEUE',
    UPDATE_ALERT_QUEUE_POSITION: 'UPDATE_ALERT_QUEUE_POSITION'
};
