export default {
	UPDATE_APPOINTMENT_ERRORS: 'UPDATE_APPOINTMENT_ERRORS',
	UPDATE_STEP_INDEX: 'UPDATE_STEP_INDEX',
	SUBMIT_APPOINTMENT: 'SUBMIT_APPOINTMENT',
	BEGIN_LOADING_TRANSITION: 'BEGIN_LOADING_TRANSITION',
	END_LOADING_TRANSITION: 'END_LOADING_TRANSITION',
	SET_SAVING_INDICATOR: 'SET_SAVING_INDICATOR',
	CLEAR_APPOINTMENT_STATE: 'CLEAR_APPOINTMENT_STATE'
};
