export const UPDATE_CONTACT_ERROR_INFO = 'UPDATE_CONTACT_ERROR_INFO';
export default {
    UPDATE_CONTACT_FIRST_NAME: 'UPDATE_CONTACT_FIRST_NAME',
    UPDATE_CONTACT_LAST_NAME: 'UPDATE_CONTACT_LAST_NAME',
    UPDATE_CONTACT_EMAIL_ADDRESS: 'UPDATE_CONTACT_EMAIL_ADDRESS',
    UPDATE_CONTACT_PHONE_NUMBER: 'UPDATE_CONTACT_PHONE_NUMBER',
    UPDATE_CONTACT_EXTENSION: 'UPDATE_CONTACT_EXTENSION',
	CLEAR_CONTACT_STATE: 'CLEAR_CONTACT_STATE',
	UPDATE_CONTACT_ERROR_INFO
};