export const UPDATE_INSTITUTION_ERROR_INFO = 'UPDATE_INSTITUTION_ERROR_INFO';
export default {
	UPDATE_INSTITUTION_NAME: 'UPDATE_INSTITUTION_NAME',
	UPDATE_INSTITUTION_STREET: 'UPDATE_INSTITUTION_STREET',
	UPDATE_INSTITUTION_CITY: 'UPDATE_INSTITUTION_CITY',
	UPDATE_INSTITUTION_STATE: 'UPDATE_INSTITUTION_STATE',
	UPDATE_INSTITUTION_ZIP: 'UPDATE_INSTITUTION_ZIP',
	UPDATE_INSTITUTION: 'UPDATE_INSTITUTION',
	SAVE_INSTITUTION: 'SAVE_INSTITUTION',
	CLEAR_INSTITUTION: 'CLEAR_INSTITUTION',
	UPDATE_INSTITUTION_ERROR_INFO
};
