export const UPDATE_QUESTIONS_ERROR_INFO = 'UPDATE_QUESTIONS_ERROR_INFO';
export default {
    UPDATE_QUESTIONS_NAME: 'UPDATE_QUESTIONS_NAME',
    UPDATE_QUESTIONS_EMAIL: 'UPDATE_QUESTIONS_EMAIL',
    UPDATE_QUESTIONS_SUBJECT: 'UPDATE_QUESTIONS_SUBJECT',
	UPDATE_QUESTIONS_BODY: 'UPDATE_QUESTIONS_BODY',
	SUBMIT_QUESTIONS: 'SUBMIT_QUESTIONS',
	CLEAR_QUESTIONS_STATE: 'CLEAR_QUESTIONS_STATE',
	SET_QUESTIONS_SAVING_INDICATOR: 'SET_QUESTIONS_SAVING_INDICATOR',
	UPDATE_QUESTIONS_ERROR_INFO
};