export const UPDATE_SCHEDULE_ERROR_INFO = 'UPDATE_SCHEDULE_ERROR_INFO';
export default {
	UPDATE_SCHEDULE_TIME: 'UPDATE_SCHEDULE_TIME',
	UPDATE_SCHEDULE_DATE: 'UPDATE_SCHEDULE_DATE',
	UPDATE_SCHEDULE_DETAILS: 'UPDATE_SCHEDULE_DETAILS',
	UPDATE_SCHEDULE_FLEXIBLE: 'UPDATE_SCHEDULE_FLEXIBLE',
	CLEAR_SCHEDULE_STATE: 'CLEAR_SCHEDULE_STATE',
	UPDATE_SCHEDULE_ERROR_INFO
};
