export default {
	LOAD_UNIVERSITIES_DATA_SOURCE: 'LOAD_UNIVERSITIES_DATA_SOURCE',
    UPDATE_UNIVERSITIES_DATA_SOURCE: 'UPDATE_UNIVERSITIES_DATA_SOURCE',
	CLEAR_UNIVERSITIES_DATA_SOURCE: 'CLEAR_UNIVERSITIES_DATA_SOURCE',
	UPDATE_UNIVERSITIES_SEARCH_TEXT: 'UPDATE_UNIVERSITIES_SEARCH_TEXT',
    CLEAR_UNIVERSITIES_SEARCH_TEXT: 'CLEAR_UNIVERSITIES_SEARCH_TEXT',
	OPEN_UNIVERSITY_SEARCH_DIALOG: 'OPEN_UNIVERSITY_SEARCH_DIALOG',
	CLOSE_UNIVERSITY_SEARCH_DIALOG: 'CLOSE_UNIVERSITY_SEARCH_DIALOG'
};
